sudo: required
services:
  - docker

before_install:
  - docker build -t sassyg/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true sassyg/react-test npm run test

after_success: 
  - docker build -t sassyg/multi-client ./client
  - docker build -t sassyg/multi-client ./nginx
  - docker build -t sassyg/multi-client ./server
  - docker build -t sassyg/multi-client ./worker
  
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u $"DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push Sospunky/multi-client
  - docker push Sospunky/multi-nginx
  - docker push Sospunky/multi-server
  - docker push Sospunky/multi-worker

#Test 

  